-- บริษัท/ผู้รับเหมา (master) + เชื่อม profiles + trigger สมัครสมาชิก

create table if not exists public."Contractors" (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

comment on table public."Contractors" is 'บริษัท / ผู้รับเหมา — เพิ่มรายการผ่าน SQL หรือผู้ดูแลระบบ';

alter table public.profiles
  add column if not exists contractor_id bigint;

alter table public.profiles
  drop constraint if exists profiles_contractor_id_fkey;

alter table public.profiles
  add constraint profiles_contractor_id_fkey
  foreign key (contractor_id) references public."Contractors"(id) on delete set null;

alter table public."Contractors" enable row level security;

drop policy if exists "cw_contractors_select_public" on public."Contractors";
create policy "cw_contractors_select_public"
  on public."Contractors" for select
  to anon, authenticated
  using (true);

-- สร้างแถว profiles พร้อมข้อมูลจาก user_metadata (รองรับยืนยันอีเมล)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  meta jsonb;
  raw_job text;
  raw_contractor text;
  jid integer;
  cid bigint;
begin
  meta := coalesce(new.raw_user_meta_data, '{}'::jsonb);

  raw_job := nullif(trim(meta->>'job_id'), '');
  jid := null;
  if raw_job is not null then
    begin
      jid := raw_job::integer;
    exception
      when others then
        jid := null;
    end;
  end if;

  if jid is not null and not exists (select 1 from public."Jobs" j where j.id = jid) then
    jid := null;
  end if;

  raw_contractor := nullif(trim(meta->>'contractor_id'), '');
  cid := null;
  if raw_contractor is not null then
    begin
      cid := raw_contractor::bigint;
    exception
      when others then
        cid := null;
    end;
  end if;

  if cid is not null and not exists (select 1 from public."Contractors" c where c.id = cid) then
    cid := null;
  end if;

  insert into public.profiles (id, fname, lname, phone, "Job", employee_id, contractor_id)
  values (
    new.id,
    nullif(trim(meta->>'fname'), ''),
    nullif(trim(meta->>'lname'), ''),
    nullif(trim(meta->>'phone'), ''),
    jid,
    nullif(trim(meta->>'employee_id'), ''),
    cid
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

-- ตัวอย่าง: insert into public."Contractors" (name) values ('ชื่อบริษัทหรือผู้รับเหมา');
